import React, { useState, useRef } from 'react';
import { motion } from 'framer-motion';
import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar, Cell } from 'recharts';
import html2canvas from 'html2canvas-pro';
import { T } from '../theme/theme.js';
import { ChartLineUp, ChartBar, Trophy, Star, CheckCircle, ArrowSquareOut, Users, CalendarCheck, PencilSimpleLine, Notebook, CaretRight, X } from '../icons/icons.jsx';
import { Card, Btn, Badge, SubjectBadge, Progress, PageHeader, Select, StatCard, BackBtn, FileIcon, Input, Textarea } from '../components/ui';
import { ShareableProgressCard, XPBar, BadgeChip, StudentAvatar } from '../components/gamification';
import { calcStudentXP, getLevel, getLevelProgress, getStudentBadges } from '../utils/gamificationUtils.js';
import { getSubject, getSubjectTheme, formatDate } from '../utils/helpers.js';
import { SUBJECTS } from '../data/subjects.js';
import { LEVELS, BADGE_DEFS, AVATAR_OPTIONS } from '../data/gamification.js';

function ProgressTracker({ state, dispatch }) {
  const [sel, setSel] = useState(null);
  const [showNewReport, setShowNewReport] = useState(false);
  const [reportMonth, setReportMonth] = useState("");
  const [reportContent, setReportContent] = useState("");
  const [editingReport, setEditingReport] = useState(null);
  const [viewingReport, setViewingReport] = useState(null);
  const [shareMsg, setShareMsg] = useState("");

  // Generate parent report text for sharing
  function generateParentReport(student) {
    const xp = calcStudentXP(student, state);
    const level = getLevel(xp);
    const gradedSubs = state.submissions.filter(s => s.studentId === student.id && s.status === "graded");
    const avgGrade = gradedSubs.length > 0 ? gradedSubs.map(s => s.grade).join(", ") : "No grades yet";
    const attendanceCount = Object.values(state.attendance).reduce((acc, rec) => acc + (rec[student.id] === "present" || rec[student.id] === "late" ? 1 : 0), 0);
    const totalSessions = Object.keys(state.attendance).length;
    return `📊 A Worthy Progress Report\n👤 Student: ${student.name}\n🎖️ Level: ${level.name} (${xp} XP)\n📋 Grades: ${avgGrade}\n📅 Attendance: ${attendanceCount}/${totalSessions} sessions\n🔥 Study Streak: ${state.wallet.streak} days\n🪙 Coins earned: ${state.wallet.coins}\n\nGenerated by A Worthy LMS · lms.a-worthy.com`;
  }

  function shareReport(student) {
    const text = generateParentReport(student);
    if (navigator.share) {
      navigator.share({ title: `${student.name} — Progress Report`, text });
    } else {
      navigator.clipboard.writeText(text);
      setShareMsg("Report copied to clipboard!");
      setTimeout(() => setShareMsg(""), 2000);
    }
  }

  if (sel) {
    const student = state.students.find((s) => s.id === sel);
    if (!student) return null;
    const scoreData = student.quizResults.map((r) => ({ date: formatDate(r.date), score: Math.round((r.score / r.total) * 100) }));
    const subjScores = {};
    student.quizResults.forEach((r) => { const q = state.quizzes.find((q) => q.id === r.quizId); if (q) { if (!subjScores[q.subject]) subjScores[q.subject] = []; subjScores[q.subject].push(Math.round((r.score / r.total) * 100)); } });
    const barData = Object.entries(subjScores).map(([s, scores]) => ({ name: getSubject(s)?.name || s, value: Math.round(scores.reduce((a, b) => a + b, 0) / scores.length), color: getSubjectTheme(s).accent }));

    return (
      <div>
        <BackBtn onClick={() => setSel(null)} />
        <Card elevated style={{ padding: "24px 32px", marginBottom: 20, borderTop: `3px solid ${T.accent}` }}>
          <div style={{ display: "flex", alignItems: "center", gap: 16, marginBottom: 20 }}>
            {(() => { const xp = calcStudentXP(student, state); const lv = getLevel(xp); return (
              <StudentAvatar student={student} size={52} radius={T.r3} />
            ); })()}
            <div style={{ flex: 1 }}>
              <h1 style={{ color: T.text, fontSize: 22, fontWeight: 800, margin: "0 0 4px", letterSpacing: -0.3 }}>{student.name}</h1>
              <div style={{ display: "flex", gap: 6, flexWrap: "wrap" }}>{student.subjects.map((s) => <SubjectBadge key={s} subjectId={s} small />)}</div>
            </div>
          </div>
          {/* XP / Level */}
          <div style={{ marginBottom: 16 }}>
            <XPBar xp={calcStudentXP(student, state)} />
          </div>
          {/* Badges */}
          {(() => {
            const badges = getStudentBadges(student, state);
            if (badges.length === 0) return null;
            return (
              <div style={{ marginBottom: 16 }}>
                <div style={{ fontSize: 12, fontWeight: 700, color: T.textSec, marginBottom: 8, letterSpacing: 0.5, textTransform: "uppercase" }}>Achievements</div>
                <div style={{ display: "flex", flexWrap: "wrap", gap: 6 }}>
                  {BADGE_DEFS.map(b => <BadgeChip key={b.id} badge={b} earned={badges.some(sb => sb.id === b.id)} size="sm" />)}
                </div>
              </div>
            );
          })()}
          {/* Avatar Picker */}
          <div>
            <div style={{ fontSize: 12, fontWeight: 700, color: T.textSec, marginBottom: 10, letterSpacing: 0.5, textTransform: "uppercase" }}>Choose Avatar</div>
            <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(48px, 1fr))", gap: 8 }}>
              {AVATAR_OPTIONS.map(av => {
                const selected = student.avatar === av.id;
                return (
                  <button key={av.id} title={av.id} onClick={() => dispatch({ type: "UPDATE_STUDENT_AVATAR", payload: { studentId: student.id, avatar: av.id } })} style={{ width: "100%", aspectRatio: "1", borderRadius: T.r2, border: `2.5px solid ${selected ? av.ring : T.border}`, background: selected ? av.bg : T.bgMuted, cursor: "pointer", fontSize: 20, display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.15s", boxShadow: selected ? `0 0 0 3px ${av.ring}33` : "none", transform: selected ? "scale(1.1)" : "scale(1)" }}>
                    {av.emoji}
                  </button>
                );
              })}
            </div>
          </div>
        </Card>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20, marginBottom: 20 }}>
          <Card elevated>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "0 0 14px" }}>Score Trend</h3>
            <ResponsiveContainer width="100%" height={200}>
              <LineChart data={scoreData}><CartesianGrid strokeDasharray="3 3" stroke={T.border} /><XAxis dataKey="date" tick={{ fontSize: 11, fill: T.textTer }} /><YAxis domain={[0, 100]} tick={{ fontSize: 11, fill: T.textTer }} /><Tooltip contentStyle={{ background: T.bgCard, border: `1px solid ${T.border}`, borderRadius: T.r2, color: T.text, fontSize: 12, boxShadow: T.shadow2 }} /><Line type="monotone" dataKey="score" stroke={T.accent} strokeWidth={2.5} dot={{ fill: T.accent, r: 4, strokeWidth: 2, stroke: T.bgCard }} activeDot={{ r: 6, fill: T.accent }} /></LineChart>
            </ResponsiveContainer>
          </Card>
          <Card elevated>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "0 0 14px" }}>Average by Subject</h3>
            <ResponsiveContainer width="100%" height={200}>
              <BarChart data={barData}><CartesianGrid strokeDasharray="3 3" stroke={T.border} /><XAxis dataKey="name" tick={{ fontSize: 10, fill: T.textTer }} /><YAxis domain={[0, 100]} tick={{ fontSize: 11, fill: T.textTer }} /><Tooltip contentStyle={{ background: T.bgCard, border: `1px solid ${T.border}`, borderRadius: T.r2, color: T.text, fontSize: 12, boxShadow: T.shadow2 }} /><Bar dataKey="value" radius={[6, 6, 0, 0]}>{barData.map((e, i) => <Cell key={i} fill={e.color} />)}</Bar></BarChart>
            </ResponsiveContainer>
          </Card>
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 20 }}>
          <Card elevated>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "0 0 14px" }}>Topic Completion</h3>
            {Object.entries(student.topicCompletion).map(([subj, topics]) => {
              const theme = getSubjectTheme(subj);
              return (
                <div key={subj} style={{ marginBottom: 18 }}>
                  <SubjectBadge subjectId={subj} small />
                  <div style={{ marginTop: 8, display: "flex", flexDirection: "column", gap: 8 }}>
                    {Object.entries(topics).map(([topic, pct]) => (
                      <div key={topic}><div style={{ display: "flex", justifyContent: "space-between", fontSize: 12, color: T.textSec, marginBottom: 4 }}><span>{topic}</span><span style={{ color: theme.accent, fontWeight: 700 }}>{pct}%</span></div><Progress value={pct} color={theme.accent} bg={theme.bg} /></div>
                    ))}
                  </div>
                </div>
              );
            })}
          </Card>
          <Card elevated>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "0 0 14px" }}>Quiz History</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {student.quizResults.map((r, idx) => {
                const quiz = state.quizzes.find((q) => q.id === r.quizId);
                const pct = Math.round((r.score / r.total) * 100);
                return (
                  <div key={idx} style={{ display: "flex", justifyContent: "space-between", alignItems: "center", padding: "10px 12px", background: T.bgMuted, borderRadius: T.r2, border: `1px solid ${T.border}` }}>
                    <div><div style={{ fontSize: 13, fontWeight: 550, color: T.text }}>{quiz?.title || "Quiz"}</div><div style={{ fontSize: 11, color: T.textTer }}>{formatDate(r.date)}</div></div>
                    <div style={{ textAlign: "right" }}><div style={{ fontSize: 16, fontWeight: 800, color: pct >= 70 ? T.success : pct >= 50 ? T.warning : T.danger }}>{pct}%</div><div style={{ fontSize: 11, color: T.textTer }}>{r.score}/{r.total}</div></div>
                  </div>
                );
              })}
            </div>
            <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "20px 0 14px" }}>Materials Accessed</h3>
            <div style={{ display: "flex", flexDirection: "column", gap: 6 }}>
              {student.materialsAccessed.map((rId) => {
                const resource = state.resources.find((r) => r.id === rId);
                if (!resource) return null;
                return <div key={rId} style={{ display: "flex", alignItems: "center", gap: 8, padding: "6px 0", fontSize: 13, color: T.text }}><div style={{ width: 26, height: 26, borderRadius: T.r1, background: resource.type === "pdf" ? T.dangerBg : resource.type === "video" ? "#DBEAFE" : T.accentLight, display: "flex", alignItems: "center", justifyContent: "center" }}><FileIcon type={resource.type} size={13} /></div>{resource.title}</div>;
              })}
            </div>
          </Card>
        </div>

        {/* ━━━ MONTHLY PROGRESS REPORTS ━━━ */}
        <div style={{ marginTop: 24 }}>
          <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: 16 }}>
            <h2 style={{ fontSize: 18, fontWeight: 700, color: T.text, margin: 0, letterSpacing: -0.3 }}>Monthly Progress Reports</h2>
            <Btn onClick={() => { setShowNewReport(!showNewReport); setEditingReport(null); setViewingReport(null); }}><PencilSimpleLine size={15} weight="bold" /> Write Report</Btn>
          </div>

          {/* New / Edit report form */}
          {(showNewReport || editingReport) && (
            <Card elevated style={{ marginBottom: 20, borderLeft: `3px solid ${T.accent}` }}>
              <h3 style={{ fontSize: 14, fontWeight: 700, color: T.text, margin: "0 0 14px" }}>
                {editingReport ? `Edit Report — ${editingReport.title}` : `New Report for ${student.name}`}
              </h3>
              {!editingReport && (
                <div style={{ marginBottom: 14 }}>
                  <Input value={reportMonth} onChange={setReportMonth} type="month" style={{ maxWidth: 220 }} />
                </div>
              )}
              <Textarea
                value={editingReport ? editingReport.content : reportContent}
                onChange={(v) => editingReport ? setEditingReport({ ...editingReport, content: v }) : setReportContent(v)}
                placeholder={`Write a progress report for ${student.name} (~300 words). Cover overall progress, subject-specific performance, strengths, areas for improvement, and recommendations for parents...`}
                rows={14}
              />
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: 14 }}>
                <div style={{ fontSize: 12, color: T.textTer }}>
                  {(editingReport ? editingReport.content : reportContent).split(/\s+/).filter(Boolean).length} words
                </div>
                <div style={{ display: "flex", gap: 8 }}>
                  <Btn variant="secondary" onClick={() => { setShowNewReport(false); setEditingReport(null); setReportContent(""); setReportMonth(""); }}><X size={14} weight="bold" /> Cancel</Btn>
                  {editingReport ? (
                    <Btn onClick={() => {
                      dispatch({ type: "UPDATE_REPORT", payload: { id: editingReport.id, content: editingReport.content } });
                      dispatch({ type: "ADD_TOAST", payload: { message: "Report updated", variant: "success" } });
                      setEditingReport(null);
                    }}><CheckCircle size={14} weight="bold" /> Save Changes</Btn>
                  ) : (
                    <Btn onClick={() => {
                      if (!reportMonth || !reportContent.trim()) return;
                      const monthLabel = new Date(reportMonth + "-01").toLocaleDateString("en-GB", { month: "long", year: "numeric" });
                      dispatch({ type: "ADD_REPORT", payload: { studentId: student.id, month: reportMonth, title: monthLabel, content: reportContent } });
                      dispatch({ type: "ADD_TOAST", payload: { message: `Report for ${monthLabel} created`, variant: "success" } });
                      setReportContent(""); setReportMonth(""); setShowNewReport(false);
                    }} disabled={!reportMonth || !reportContent.trim()}><CheckCircle size={14} weight="bold" /> Save Report</Btn>
                  )}
                </div>
              </div>
            </Card>
          )}

          {/* Viewing a report */}
          {viewingReport && (
            <Card elevated style={{ marginBottom: 20, borderTop: `3px solid ${T.accent}` }}>
              <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 16 }}>
                <div>
                  <h3 style={{ fontSize: 16, fontWeight: 700, color: T.text, margin: "0 0 6px" }}>{viewingReport.title}</h3>
                  <div style={{ display: "flex", gap: 8, alignItems: "center" }}>
                    <span style={{ fontSize: 12, color: T.textTer }}>Written {formatDate(viewingReport.createdAt)}</span>
                    {viewingReport.sharedWithParents
                      ? <Badge color={T.success} bg={T.successBg}><CheckCircle size={11} weight="fill" /> Shared with Parents</Badge>
                      : <Badge color={T.textSec} bg={T.bgMuted}>Draft</Badge>
                    }
                  </div>
                </div>
                <div style={{ display: "flex", gap: 6 }}>
                  <Btn size="sm" variant="secondary" onClick={() => { setEditingReport({ ...viewingReport }); setViewingReport(null); setShowNewReport(false); }}><PencilSimpleLine size={13} weight="bold" /> Edit</Btn>
                  {!viewingReport.sharedWithParents ? (
                    <Btn size="sm" onClick={() => {
                      dispatch({ type: "SHARE_REPORT", payload: viewingReport.id });
                      dispatch({ type: "ADD_TOAST", payload: { message: "Report shared with parents", variant: "success" } });
                      setViewingReport({ ...viewingReport, sharedWithParents: true });
                    }}><ArrowSquareOut size={13} weight="bold" /> Share with Parents</Btn>
                  ) : (
                    <Btn size="sm" variant="danger" onClick={() => {
                      dispatch({ type: "UNSHARE_REPORT", payload: viewingReport.id });
                      dispatch({ type: "ADD_TOAST", payload: { message: "Report unshared", variant: "info" } });
                      setViewingReport({ ...viewingReport, sharedWithParents: false });
                    }}><X size={13} weight="bold" /> Unshare</Btn>
                  )}
                  <Btn size="sm" variant="ghost" onClick={() => setViewingReport(null)}><X size={13} weight="bold" /></Btn>
                </div>
              </div>
              <div style={{ fontSize: 14, color: T.text, lineHeight: 1.8, whiteSpace: "pre-wrap", background: T.bgMuted, padding: "20px 24px", borderRadius: T.r2, border: `1px solid ${T.border}` }}>
                {viewingReport.content}
              </div>
              <div style={{ marginTop: 12, fontSize: 12, color: T.textTer, textAlign: "right" }}>
                {viewingReport.content.split(/\s+/).filter(Boolean).length} words
              </div>
            </Card>
          )}

          {/* Report list */}
          {!viewingReport && !editingReport && (() => {
            const studentReports = state.reports.filter(r => r.studentId === student.id).sort((a, b) => b.month.localeCompare(a.month));
            if (studentReports.length === 0) return (
              <Card elevated style={{ textAlign: "center", padding: 40 }}>
                <div style={{ width: 56, height: 56, borderRadius: T.r3, background: T.accentLight, display: "inline-flex", alignItems: "center", justifyContent: "center", marginBottom: 14 }}>
                  <Notebook size={24} weight="duotone" color={T.accent} />
                </div>
                <p style={{ fontSize: 14, color: T.textSec, fontWeight: 500, margin: "0 0 12px" }}>No progress reports yet</p>
                <Btn onClick={() => setShowNewReport(true)}><PencilSimpleLine size={14} weight="bold" /> Write First Report</Btn>
              </Card>
            );
            return (
              <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
                {studentReports.map(report => (
                  <Card key={report.id} onClick={() => { setViewingReport(report); setShowNewReport(false); setEditingReport(null); }} elevated style={{ padding: 18, borderLeft: `3px solid ${report.sharedWithParents ? T.success : T.accent}` }}>
                    <div style={{ display: "flex", alignItems: "center", gap: 14 }}>
                      <div style={{ width: 44, height: 44, borderRadius: T.r2, background: report.sharedWithParents ? T.successBg : T.accentLight, display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 }}>
                        <Notebook size={20} weight="duotone" color={report.sharedWithParents ? T.success : T.accent} />
                      </div>
                      <div style={{ flex: 1 }}>
                        <div style={{ fontSize: 14, fontWeight: 650, color: T.text }}>{report.title}</div>
                        <div style={{ display: "flex", gap: 8, alignItems: "center", marginTop: 4 }}>
                          <span style={{ fontSize: 12, color: T.textTer }}>Written {formatDate(report.createdAt)}</span>
                          {report.sharedWithParents
                            ? <Badge color={T.success} bg={T.successBg} style={{ fontSize: 10 }}><CheckCircle size={11} weight="fill" /> Shared</Badge>
                            : <Badge color={T.textSec} bg={T.bgMuted} style={{ fontSize: 10 }}>Draft</Badge>
                          }
                        </div>
                      </div>
                      <div style={{ fontSize: 12, color: T.textTer, textAlign: "right", flexShrink: 0 }}>
                        {report.content.split(/\s+/).filter(Boolean).length} words
                      </div>
                      <CaretRight size={16} weight="bold" color={T.textTer} />
                    </div>
                  </Card>
                ))}
              </div>
            );
          })()}
        </div>
      </div>
    );
  }

  return (
    <div>
      <PageHeader title="Student Progress" subtitle="Track performance and completion" />
      <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fill, minmax(340px, 1fr))", gap: 16 }}>
        {state.students.map((student) => {
          const avg = student.quizResults.length > 0 ? Math.round(student.quizResults.reduce((sum, r) => sum + (r.score / r.total) * 100, 0) / student.quizResults.length) : 0;
          const xp = calcStudentXP(student, state);
          const lv = getLevel(xp);
          const badges = getStudentBadges(student, state);
          return (
            <Card key={student.id} onClick={() => setSel(student.id)} elevated>
              <div style={{ display: "flex", alignItems: "center", gap: 14, marginBottom: 14 }}>
                <StudentAvatar student={student} size={48} radius={T.r3} />
                <div style={{ flex: 1 }}>
                  <div style={{ fontSize: 15, fontWeight: 650, color: T.text }}>{student.name}</div>
                  <div style={{ display: "flex", gap: 4, marginTop: 5, flexWrap: "wrap", alignItems: "center" }}>
                    {student.subjects.map((s) => <SubjectBadge key={s} subjectId={s} small />)}
                    <span style={{ fontSize: 10, fontWeight: 700, color: lv.color, background: lv.bg, padding: "2px 7px", borderRadius: 20, marginLeft: 2 }}>{lv.emoji} {lv.name}</span>
                  </div>
                </div>
              </div>
              {/* XP bar compact */}
              <div style={{ marginBottom: 12 }}>
                <XPBar xp={xp} compact />
              </div>
              <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr", gap: 10, textAlign: "center", marginBottom: badges.length > 0 ? 12 : 0 }}>
                <div style={{ padding: 10, background: T.accentLight, borderRadius: T.r2 }}><div style={{ fontSize: 20, fontWeight: 800, color: T.accent }}>{student.quizResults.length}</div><div style={{ fontSize: 11, color: T.textTer }}>Quizzes</div></div>
                <div style={{ padding: 10, background: avg >= 70 ? T.successBg : avg >= 50 ? T.warningBg : T.dangerBg, borderRadius: T.r2 }}><div style={{ fontSize: 20, fontWeight: 800, color: avg >= 70 ? T.success : avg >= 50 ? T.warning : T.danger }}>{avg}%</div><div style={{ fontSize: 11, color: T.textTer }}>Avg Score</div></div>
                <div style={{ padding: 10, background: lv.bg, borderRadius: T.r2 }}><div style={{ fontSize: 20, fontWeight: 800, color: lv.color, fontFamily: "'JetBrains Mono', monospace" }}>{xp}</div><div style={{ fontSize: 11, color: T.textTer }}>XP</div></div>
              </div>
              {badges.length > 0 && (
                <div style={{ display: "flex", gap: 4, flexWrap: "wrap" }}>
                  {badges.map(b => <span key={b.id} title={b.name} style={{ fontSize: 16 }}>{b.emoji}</span>)}
                </div>
              )}
            </Card>
          );
        })}
      </div>
    </div>
  );
}

/* ━━━ ATTENDANCE ━━━ */

export default ProgressTracker;
